In [1]:
import numpy as np

In [6]:
data1 = [6,7,8,9]
arr1 = np.array(data1)
print(type(arr1))
print(type(data1))


<class 'numpy.ndarray'>
<class 'list'>


In [7]:
print(arr1.dtype)

int64


In [9]:
arr1.ndim
arr1.shape

(4,)

In [10]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [20]:
print([x for x in range(10)])


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [22]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [25]:
arr1 = np.array(data1, dtype=np.float64)
arr1.dtype

dtype('float64')

In [28]:
arr1 = np.array(data1, dtype=np.int32)
arr1

array([6, 7, 8, 9], dtype=int32)

In [30]:
arr3 = arr1.astype(np.float64)
arr3.dtype

dtype('float64')

In [31]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
arr4 = arr2 + arr3
print(arr2)
print(arr3)
arr4

[[1 2 3 4]
 [5 6 7 8]]
[6. 7. 8. 9.]


array([[ 7.,  9., 11., 13.],
       [11., 13., 15., 17.]])

In [37]:
arr5 = arr2 + 4
print(arr5)

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
print(arr1)
print(arr1[2])
print(arr5[1][2])

[6 7 8 9]
8
11


In [53]:
arr6 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr6 = np.array(arr6)
print(arr6)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
arr6.ndim
print(arr6.shape)

(2, 2, 3)


In [58]:
arr6[0][0][1]

2

In [60]:
names = np.array(["bmw","tesla","benz","python"])
names

array(['bmw', 'tesla', 'benz', 'python'], dtype='<U6')

In [ ]:
names[names != "bmw"]

array(['tesla', 'benz', 'python'], dtype='<U6')

In [70]:
arr9 = arr2.reshape(4,2)
print(arr2.ravel('F'))
print(arr2)
print(arr9)

[1 5 2 6 3 7 4 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(arr2.ceil()
print(arr2min)

[[0 0 1 1]
 [1 2 2 2]]
1


In [ ]:
import matplotlib.pyplot as plt



AttributeError: module 'matplotlib.pyplot' has no attribute 'ti'

In [85]:
#arr9 = np.array([1,2,3,4,5,6,8])
np.save("savearr9",arr9)

In [86]:
!ls -ltr

total 120
-rw-r--r--  1 varala  staff   110 Nov  8 13:30 hello_world.py
-rw-r--r--  1 varala  staff   339 Nov  8 13:54 data_type.py
-rw-r--r--  1 varala  staff    39 Nov  8 13:57 README.md
-rw-r--r--  1 varala  staff   103 Nov 11 13:07 execise1.py
-rw-r--r--  1 varala  staff   819 Nov 11 13:51 List_method.py
-rw-r--r--  1 varala  staff   236 Nov 11 14:06 string_datatype.py
-rw-r--r--  1 varala  staff   766 Nov 12 15:38 functions.py
-rw-r--r--  1 varala  staff   175 Nov 12 16:23 StandardFunction.py
-rw-r--r--  1 varala  staff   256 Nov 15 12:30 sets.py
-rw-r--r--  1 varala  staff   301 Nov 15 12:40 dict_comperhension.py
-rw-r--r--  1 varala  staff  3234 Nov 15 13:09 new_test.ipynb
-rw-r--r--  1 varala  staff   192 Nov 15 14:20 savearr9.npy
-rw-r--r--  1 varala  staff  9602 Nov 15 14:20 numpy.ipynb


In [88]:
print(np.load('savearr9.npy'))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [89]:
!cat savearr9.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (4, 2), }                                                          
